notifications:
  slack: geekshubs:S32At4pC3DX58sqtloCFQXyz
  template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
dist: trusty
sudo: required
notifications:
  email: false
  
language: bash

before_script:
  - pwd
  - ls -ltra
  - git version
  
script:
- chmod +x scripts/deploy.sh
- scripts/deploy.sh '103-tj-vicboma1'

after_script:
  - pwd
  - ls -ltra
