language: bash
before_script:
  - echo date
script:
- |
  if [ "$TRAVIS_BRANCH == "master" ]; then
    scripts/deploy.sh staging
  elif
    scripts/deploy.sh production
    
notifications:
  email: false
