dist: trusty
sudo: required
notifications:
  email: false
  slack: geekshubs:rrvY2RwjwpXwVTW3jjcW8JYg
  
language: bash

before_script:
  - pwd
  - ls -ltra
  - git version
  
script:
- chmod +x scripts/deploy.sh
- scripts/deploy.sh 'U2FsdGVkX1/2+RnH78z85cRUsF1A6QAeGo4Es/atPlQ='

after_script:
  - pwd
  - ls -ltra
