dist: trusty
sudo: required
notifications:
  email: false
  slack: geekshubs:rrvY2RwjwpXwVTW3jjcW8JYg
  
language: bash

before_script: 
  - pwd
  - ls -ltra
  - git version
  
script:
- chmod +x scripts/deploy.sh
- scripts/deploy.sh 'U2FsdGVkX196cP/wSXuLKgsi3RGdNywYyCUNl6A6C1o='

after_script:
  - pwd
  - ls -ltra
