dist: trusty
notifications:
  email: false
  slack: geekshubs:rrvY2RwjwpXwVTW3jjcW8JYg
language: shell
before_script: 
  - pwd
  - ls -ltra
  - git version

script:
- chmod +x scripts/deploy.sh 
- scripts/deploy.sh 'MjAxLXRtai1weS12aWNib21hMQo='
 
after_script:
  - pwd
  - ls -ltra
