dist: trusty
sudo: required
notifications:
  email: false
  
language: bash

before_script:
  - pwd
  - ls -ltra
  - git version
  
script:
- chmod +x scripts/deploy.sh
- scripts/deploy.sh

after_script:
  - pwd
  - ls -ltra
